Finishing my Portfolio
bhskr44/MyPortfolio pull request #2
Opened 2022-09-22 14:42 UTC by bhskr44

For the first milestone in the process of creating your portfolio website, we need to set up a new repository and prepare it for development using best practices (e.g. liters). building all the sections of the mobile website using the template we choose a predetermined design given by Microverse.

2022-09-23 15:31 UTC, jerryowusu requested changes
Hi @bhskr44 :wink:, 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses:

![almost there](https://user-images.githubusercontent.com/65233860/191997774-53e45daf-cdd2-46af-a583-0a49251b59d4.jpg)


## Highlights
:heavy_check_mark: Good commit messages
:heavy_check_mark: Neat and well organized code
:heavy_check_mark: Excellent readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 15:31 UTC, jerryowusu commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
[OPTIONAL] You might consider taking this out of the readme file since it is just an instruction to help guide you. It does not need to be in the final version.

2022-09-23 15:31 UTC, jerryowusu commented on css/main.css
> +}
Kindly use CSS Grid for the main container that contains all of the individual work cards as stated in the project requirements below (check bullet point number 2)

![Screenshot from 2022-09-23 12-45-52](https://user-images.githubusercontent.com/65233860/191989296-bad51ba6-cdb9-49c6-9b99-4c322dfce903.png)

2022-09-23 15:31 UTC, jerryowusu commented on index.html
> +          <div class="social">LET’S CONNECT</div>
Kindly use an hx (h2-h6) tag for this one since it is a title/header instead of a div tag.

2022-09-23 15:31 UTC, jerryowusu commented on index.html
> +        </div>
As stated in the project requirements, kindly use ul and li tags for the categories in `About Myself` section. Please make sure that the `Languages`, `Frameworks`, and `Skills` all use the ul and li tags. (check bullet point number 4)

![Screenshot from 2022-09-23 12-45-52](https://user-images.githubusercontent.com/65233860/191992447-7cf671f3-1141-4634-99c3-794f058385ed.png)

2022-09-23 15:31 UTC, jerryowusu commented on css/main.css
> +
Please kindly implement the active, pressed and hover effects of all the buttons. It is true that these effects are not seen on mobile versions but it is a must to implement them at this stage of the project :stuck_out_tongue_winking_eye:  You can check the desktop side of the figma design for the button effects. :pray:

2022-09-23 15:31 UTC, jerryowusu commented on index.html
> +              <i class="fa fa-angle-down" aria-hidden="true"></i>
I am really impressed with your project so far. Keep it up. However, this sections feels cramped and not really conforming to the figma design. Kindly check the font-family, font-size, weight, padding and margins and make sure they are as close to the figma design as possible. 


Figma design
![Screenshot from 2022-09-23 15-24-33](https://user-images.githubusercontent.com/65233860/191996455-089cae23-3e1c-4ded-a093-04528be0ebeb.png)


Your design
![Screenshot from 2022-09-23 15-25-17](https://user-images.githubusercontent.com/65233860/191996570-ad20a4d1-d94d-4a18-a0d0-84cab04b4b94.png)

2022-09-24 16:40 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @bhskr44 :wave:

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

:heavy_check_mark: Following the GitHub Flow
:heavy_check_mark: Descriptive PR Summary
:heavy_check_mark: Descriptive PR Title

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 16:43 UTC, merged